version: '3.7'

services:
  app:
    container_name: ${NAME}
    image: ${IMAGE}:latest
    ports:
      - 3000:3000
    environment:
      GRAPHQL_DEBUG: '1'
      PLAYGROUND_ENABLE: '1'
      SWAGGER_ENABLE: '1'
    depends_on:
      - keycloak
      - postgres

  keycloak:
    image: jboss/keycloak:latest
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./realm-export.json:/realm-export.json:ro
    environment:
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_PASSWORD: postgres
      DB_SCHEMA: public
      DB_USER: postgres
      DB_VENDOR: POSTGRES
      KEYCLOAK_IMPORT: /realm-export.json
      KEYCLOAK_MIGRATION_STRATEGY: OVERWRITE_EXISTING
      KEYCLOAK_PASSWORD: pass
      KEYCLOAK_USER: admin
      PROXY_ADDRESS_FORWARDING: 'true'
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_MULTIPLE_DATABASES: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./pginit.sh:/docker-entrypoint-initdb.d/pginit.sh:ro
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: data-${NAME}
